package com.cbit;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author cbit10
 */
public class Calculator extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	double firstnum;
    double secondnum;
    double result;
    String operations;
    /**
     * Creates new form CalculatorRoundButtons
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                       
    private void initComponents() {

        jTextDisplay = new javax.swing.JTextField();
        jBtnDivide = new javax.swing.JButton();
        jBtnBackspace = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnMinus = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnPlus = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnMultiply = new javax.swing.JButton();
        jBtnPoint = new javax.swing.JButton();
        jBtnPM = new javax.swing.JButton();
        jBtnEquals = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ujjawal Calculator");
        setBackground(new java.awt.Color(0, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextDisplay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 312, 65));

        jBtnDivide.setBackground(new java.awt.Color(204, 204, 204));
        jBtnDivide.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnDivide.setForeground(new java.awt.Color(255, 0, 0));
        jBtnDivide.setText("/");
        jBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 70, 61));

        jBtnBackspace.setBackground(new java.awt.Color(204, 204, 204));
        jBtnBackspace.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnBackspace.setForeground(new java.awt.Color(255, 0, 0));
        jBtnBackspace.setText("<-");
        jBtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackspaceActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 61));

        jBtn7.setBackground(new java.awt.Color(204, 204, 204));
        jBtn7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn7.setForeground(new java.awt.Color(255, 0, 0));
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 61));

        jBtn4.setBackground(new java.awt.Color(204, 204, 204));
        jBtn4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn4.setForeground(new java.awt.Color(255, 0, 0));
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 61));

        jBtn1.setBackground(new java.awt.Color(204, 204, 204));
        jBtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn1.setForeground(new java.awt.Color(255, 0, 0));
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 61));

        jBtn0.setBackground(new java.awt.Color(204, 204, 204));
        jBtn0.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn0.setForeground(new java.awt.Color(255, 0, 0));
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 61));

        jBtn8.setBackground(new java.awt.Color(204, 204, 204));
        jBtn8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn8.setForeground(new java.awt.Color(255, 0, 0));
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 61));

        jBtn5.setBackground(new java.awt.Color(204, 204, 204));
        jBtn5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn5.setForeground(new java.awt.Color(255, 0, 0));
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, 61));

        jBtn9.setBackground(new java.awt.Color(204, 204, 204));
        jBtn9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn9.setForeground(new java.awt.Color(255, 0, 0));
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 70, 61));

        jBtnMinus.setBackground(new java.awt.Color(204, 204, 204));
        jBtnMinus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnMinus.setForeground(new java.awt.Color(255, 0, 0));
        jBtnMinus.setText("-");
        jBtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 70, 61));

        jBtn6.setBackground(new java.awt.Color(204, 204, 204));
        jBtn6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn6.setForeground(new java.awt.Color(255, 0, 0));
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 70, 61));

        jBtnPlus.setBackground(new java.awt.Color(204, 204, 204));
        jBtnPlus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnPlus.setForeground(new java.awt.Color(255, 0, 0));
        jBtnPlus.setText("+");
        jBtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 70, 61));

        jBtn2.setBackground(new java.awt.Color(204, 204, 204));
        jBtn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn2.setForeground(new java.awt.Color(255, 0, 0));
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 70, 61));

        jBtn3.setBackground(new java.awt.Color(204, 204, 204));
        jBtn3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtn3.setForeground(new java.awt.Color(255, 0, 0));
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 70, 61));

        jBtnMultiply.setBackground(new java.awt.Color(204, 204, 204));
        jBtnMultiply.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnMultiply.setForeground(new java.awt.Color(255, 0, 0));
        jBtnMultiply.setText("*");
        jBtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 70, 61));

        jBtnPoint.setBackground(new java.awt.Color(204, 204, 204));
        jBtnPoint.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnPoint.setForeground(new java.awt.Color(255, 0, 0));
        jBtnPoint.setText(".");
        jBtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPointActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 70, 61));

        jBtnPM.setBackground(new java.awt.Color(204, 204, 204));
        jBtnPM.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnPM.setForeground(new java.awt.Color(255, 0, 0));
        jBtnPM.setText("+/-");
        jBtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 70, 61));

        jBtnEquals.setBackground(new java.awt.Color(204, 204, 204));
        jBtnEquals.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnEquals.setForeground(new java.awt.Color(255, 0, 0));
        jBtnEquals.setText("=");
        jBtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 70, 61));

        jBtnClear.setBackground(new java.awt.Color(204, 204, 204));
        jBtnClear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnClear.setForeground(new java.awt.Color(255, 0, 0));
        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, 61));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {                                           
        firstnum = Double.parseDouble(jTextDisplay.getText());
        jTextDisplay.setText("");
        operations = "/";
    }                                          

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {                                      
       String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn5.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn5.getText();
            jTextDisplay.setText(EnterNumber);
        }

    }                                     

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {                                      
       String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn9.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn9.getText();
            jTextDisplay.setText(EnterNumber);
        }

    }                                     

    private void jBtnMinusActionPerformed(java.awt.event.ActionEvent evt) {                                          
        firstnum = Double.parseDouble(jTextDisplay.getText());
        jTextDisplay.setText("");
        operations = "-";
    }                                         

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {                                      
       String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn6.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn6.getText();
            jTextDisplay.setText(EnterNumber);
        }

    }                                     

    private void jBtnPlusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        firstnum = Double.parseDouble(jTextDisplay.getText());
        jTextDisplay.setText("");
        operations = "+";
    }                                        

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn2.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn2.getText();
            jTextDisplay.setText(EnterNumber);
        }
    }                                     

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn3.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn3.getText();
            jTextDisplay.setText(EnterNumber);
        }
    }                                     

    private void jBtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {                                             
        firstnum = Double.parseDouble(jTextDisplay.getText());
        jTextDisplay.setText("");
        operations = "*";
    }                                            

    private void jBtnPointActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(! jTextDisplay.getText().contains(".")) {
            jTextDisplay.setText(jTextDisplay.getText() + jBtnPoint.getText());
        }
    }                                         

    private void jBtnPMActionPerformed(java.awt.event.ActionEvent evt) {                                       
        double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = ops * (-1);
        jTextDisplay.setText(String.valueOf(ops));
    }                                      

    private void jBtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String answer;
        secondnum = Double.parseDouble(jTextDisplay.getText());
        if(operations == "+") {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
        else if(operations == "-") {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
        else if(operations == "*") {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
        else if(operations == "/") {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
    }                                          

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {                                          
        jTextDisplay.setText("");
    }                                         

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn4.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn4.getText();
            jTextDisplay.setText(EnterNumber);
        }

    }                                     

    private void jTextDisplayActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn7.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn7.getText();
            jTextDisplay.setText(EnterNumber);
        }
    }                                     

    private void jBtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        String backspace = null;
        if(jTextDisplay.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(jTextDisplay.getText());
            sb.deleteCharAt(jTextDisplay.getText().length() - 1);
            backspace = sb.toString();
            jTextDisplay.setText(backspace);
        }
        
    }                                             

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn8.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn8.getText();
            jTextDisplay.setText(EnterNumber);
        }

    }                                     

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
         String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn1.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn1.getText();
            jTextDisplay.setText(EnterNumber);
        }
    }                                     

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {                                      
         String EnterNumber = jTextDisplay.getText();
        if(EnterNumber == "")
            jTextDisplay.setText(jBtn0.getText());
        else {
            EnterNumber = jTextDisplay.getText() + jBtn0.getText();
            jTextDisplay.setText(EnterNumber);
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnBackspace;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDivide;
    private javax.swing.JButton jBtnEquals;
    private javax.swing.JButton jBtnMinus;
    private javax.swing.JButton jBtnMultiply;
    private javax.swing.JButton jBtnPM;
    private javax.swing.JButton jBtnPlus;
    private javax.swing.JButton jBtnPoint;
    private javax.swing.JTextField jTextDisplay;
    // End of variables declaration                   
}
